config/routes.rb
Rails.application.routes.draw do
  resources :projects, only:[:index, :new, :create]
  root to: 'projects#index'
  get 'search', to: 'projects#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :first_name, presence: true, length:{ maximum:30}
  validates :last_name, presence: true, length:{ maximum:30}
  validates :age, presence: true, length:{ maximum:30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true)
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_url
    else
      render :new
    end
  end
  
  private
  
  def project_params
    params.require(:project).permit(:first_name, :last_name, :age)
  end  
  
  def search_params
    params.require(:q).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :first_name_cont, 'search form' %>
  <%= f.search_field :first_name_cont %>
  
  <%= f.submit '検索' %>
<% end %>

app/views/projects/index.html.erb
<h1>Name List</h1>

<%= render 'search_form' %>

<p>Name</p>
<% @projects.each do |user| %>
  <ul>
    <li><%= user.first_name + user.last_name %></li>
  </ul>
<% end %>

<%= link_to 'New Name', new_project_path %>

app/views/projects/new.html.erb
<h2>New Form</h2>

<%= form_with model:@project do |f| %>
  <label>First Name</label>
  <%= f.text_field :first_name %>
  <label>Last Name</label>
  <%= f.text_field :last_name %>
  <label>age</label>
  <%= f.text_field :age %>
  
  <%= f.submit '保存' %>
<% end %>